/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Ticketerie API
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  createdAt?: string;
  email?: string;
  exp?: number;
  familyName?: string;
  givenName?: string;
  iat?: number;
  id?: number;
  locale?: string;
  name?: string;
  picture?: string;
  provider?: string;
  providerId?: string;
  updatedAt?: string | null;
  userType?: string;
}
