/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Ticketerie API
 * OpenAPI spec version: 1.0.0
 */
import type { EventTeam } from './eventTeam';
import type { EventPlayer } from './eventPlayer';
import type { EventGeneric } from './eventGeneric';

export type Event = EventTeam | EventPlayer | EventGeneric;
