/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Ticketerie API
 * OpenAPI spec version: 1.0.0
 */

export * from './championship';
export * from './event';
export * from './eventDescription';
export * from './eventGeneric';
export * from './eventPlayer';
export * from './eventTeam';
export * from './eventType';
export * from './getEventById200';
export * from './getEventsParams';
export * from './location';
export * from './loginWithGoogleBody';
export * from './player';
export * from './postApiAuthLoginGoogleNativeBody';
export * from './postLoginGoogleNative200';
export * from './postLoginGoogleNativeBody';
export * from './refreshTokenBody';
export * from './searchEvent';
export * from './searchEventsParams';
export * from './searchTeam';
export * from './searchTeamsParams';
export * from './sport';
export * from './team';
export * from './teamDetail';
export * from './ticket';
export * from './ticketing';
export * from './tokenResponse';
export * from './user';