/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Ticketerie API
 * OpenAPI spec version: 1.0.0
 */

export interface Player {
  createdAt: string;
  id: number;
  name: string;
  sportId: number;
  updatedAt: string | null;
}
