/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Ticketerie API
 * OpenAPI spec version: 1.0.0
 */
import type { EventTeam } from './eventTeam';
import type { Championship } from './championship';
import type { Location } from './location';
import type { Sport } from './sport';

export interface TeamDetail {
  awayEvents: EventTeam[];
  championships: Championship[];
  championshipsId: number[];
  createdAt: string;
  homeEvents: EventTeam[];
  icon: string;
  id: number;
  location: Location;
  locationId: number;
  name: string;
  sport: Sport;
  sportId: number;
  updatedAt?: string | null;
}
