/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Ticketerie API
 * OpenAPI spec version: 1.0.0
 */

export interface Ticketing {
  createdAt: string;
  icon: string;
  id: number;
  name: string;
  updatedAt: string | null;
}
