openapi: 3.0.0
info:
  title: Ticketerie API
  version: 1.0.0
paths:
  /api/auth/login/google/native:
    summary: Login with Google
    post:
      operationId: loginWithGoogle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idToken:
                  type: string
      responses:
        "200":
          description: User data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
  /api/auth/refresh-token:
    summary: Refresh token
    post:
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        "200":
          description: User data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
  /api/user:
    get:
      operationId: getUser
      responses:
        "200":
          description: User data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
components:
  schemas:
    TokenResponse:
      type: object
      required:
        - token
        - refreshToken
      properties:
        token:
          type: string
        refreshToken:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
        providerId:
          type: string
        provider:
          type: string
        userType:
          type: string
        email:
          type: string
        name:
          type: string
        givenName:
          type: string
        familyName:
          type: string
        picture:
          type: string
        locale:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
          nullable: true
        iat:
          type: integer
        exp:
          type: integer
